### PR TITLE
CodeMirror support. Improved image support.

### LINKED ISSUE #9: Set attributes that provide runtime environment hints
We've been using the convention of setting implicit attributes that identify the runtime environment to allow other settings, such as imagesdir, to be setup properly.

I recommend setting the following implicit attributes for gist.asciidoctor.org:

* `env=docgist`
* `env-docgist`
* `platform=opal`
* `platform-opal`

This might be used to setup the imagesdir as follows:

```
:imagesdir: images
ifdef::env-docgist[]
:imagesdir: https://github.com/asciidoctor/asciidoctor/raw/master/images
endif::[]
```

In contrast, when the document is converted on the GitHub servers, the attributes `env=github` and `env-github` are set.

### LINKED ISSUE #17: Absolute image paths on GitHub
I think that an absolute image path in a document rendered from GitHub should refer to the root of the repository. Currently, it doesn't work.

You can see an example here: http://gist.asciidoctor.org/?github-powerman%2Fasciidoc-cheatsheet%2F%2FREADME.adoc (look for the screenshot)

This is definitely an edge case and I'm wondering if it should work. Really, a document shouldn't be relying on absolute paths because then it won't work when used locally (only on a web server). But I'm filing this issue for reference in case people come across the use case and are curious about it...regardless of what we decide to do.

### PR DESCRIPTION
**Pull request by nawroth**
* Adds code to load Javascript libs dynamically.
  And execute them in the correct order.
* Adds CodeMirror support.
* Makes  highlight.js load dynamically.
* Removes additional '/' present in some image URLs.
* Removes document name from image path in some cases.
* Tries to handle root-relative image paths. Fixes #17.
* Sets docgist environment variables. Fixes #9.
* Activates the toc macro by default.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks excellent!

Makes me wonder if we should have CodeMirror support in Asciidoctor as well. I'm losing my mind a bit with all the syntax highlighting options already, but JavaScript ones are easy to support so perhaps it isn't too much of a headache.

**Comment by mojavelinux** [comment]
Is CodeMirror much better than the alternatives?

**Comment by nawroth** [comment]
CodeMirror is different as you can use it for editors as well. That's what we use in the Neo4j web UI, and thus I wanted to use it for other syntax highlighting too. No idea about which one is better really.

**Comment by mojavelinux** [comment]
Aha, that makes sense. You use it for consistency across the interface. Now I understand.

I still wonder whether it makes sense to integrate into Asciidoctor core. If so, perhaps you can file an issue and we'll look into it.

There's also an outstanding request for Prism. I sort of wish the JavaScript-based highlighters would align a bit.

**Comment by nawroth** [comment]
See also #17

**Comment by nawroth** [comment]
@mojavelinux Sorry for this "all the things" commit/PR. If we want to revert part of it, I can do that by hand.

**Comment by mojavelinux** [comment]
Not a problem at all. While finer grain commits are ideal, sometimes
getting it all in there takes precedence. Onwards!

**Pull request merged**
